"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-dsp' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""
import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex',
    'scitex_decorators',
    'scitex_gen._norm',
    'scitex_gen._to_even',
    'scitex_gen._to_odd',
    'scitex_io',
    'scitex_nn._Filters',
    'scitex_nn._Hilbert',
    'scitex_nn._ModulationIndex',
    'scitex_nn._PAC',
    'scitex_nn._PSD',
    'scitex_nn._Wavelet',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-dsp's declared cross-package dependency must succeed."""
    importlib.import_module(module_name)
