"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-dsp' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex_decorators",
    "scitex_dev",
    "scitex_gen",
    "scitex_nn._Filters",
    "scitex_nn._Hilbert",
    "scitex_nn._ModulationIndex",
    "scitex_nn._PAC",
    "scitex_nn._PSD",
    "scitex_nn._Wavelet",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_dependency_imports_as_module_with_matching_name(module_name):
    """Importing scitex-dsp's declared cross-package dependency must
    succeed and return a module whose ``__name__`` matches what we asked
    for (rejects shim modules that re-export under a different name)."""
    # Arrange
    # Act
    mod = pytest.importorskip(module_name)
    # Assert
    assert mod.__name__ == module_name
