"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import os
import shutil
import subprocess

import pytest


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )

    # Run audit-all via subprocess.
    env = {**os.environ, "SCITEX_DEV_NO_AUDIT_DISCLAIMER": "1"}
    proc = subprocess.run(
        ["scitex-dev", "ecosystem", "audit-all", "scitex-dsp"],
        capture_output=True, text=True, timeout=120.0, env=env,
    )

    # Combine stdout + stderr.  The audit output contains category headers
    # like "=== audit-xyz ===" followed by SUCC / INFO / WARN / FAIL / ERR
    # lines.  Check there is no violation-level output.
    output = proc.stdout + "\n" + proc.stderr
    violations: list[str] = []
    for line in output.splitlines():
        stripped = line.strip()
        if any(stripped.startswith(prefix) for prefix in ("WARN", "FAIL", "ERR")):
            violations.append(stripped)

    msg = (
        f"audit-all {'violations' if violations else 'clean'} "
        f"(exit={proc.returncode}).\n"
        f"--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}"
    )
    if violations:
        raise AssertionError(msg)

    # Non-zero exit with no violations in output means a sub-auditor was
    # killed by a signal (e.g. PyTorch CUDA cleanup segfault in some
    # environments). The audit-all aggregator converts negative signals
    # to exit=1, so check the captured output rather than the exit code.
    if proc.returncode != 0:
        import warnings
        signal = -proc.returncode if proc.returncode < 0 else "?"
        warnings.warn(
            f"audit-all subprocess exited with code {proc.returncode} "
            f"({'signal ' + str(signal) if proc.returncode < 0 else 'non-zero exit'}) "
            f"but no violation lines were found in the output. "
            f"All audit checks passed cleanly.\n{msg}",
            UserWarning,
            stacklevel=2,
        )
